### ISSUE TITLE
html design for our automated emails

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#735] opened 2014-03-28 16:33 UTC
Much of our user support burden is because of users who respond to our automated emails. In the case of FMS, it's generally the questionnaire email, and chasing us (because they think we're the council) by replying to the confrmation email.

I suggest that we may be able to minimise this effect through design - official branding and a button rather than plain text and a link may make it clearer that the message is not from a human.

**Comment by abimysoc** [comment] 2016-03-30 15:57
#1281 is a duplicate of this and looks like the more useful one to leave open, since it has design mockups in.

**Closed by abimysoc** 2016-03-30 15:57 UTC
Labels: Backlog, UK Admin, UK specific, UK Users
