### ISSUE TITLE
FMS emails in dark mode: logo alpha channel problem

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/fixmystreet#4239] opened 2022-12-23 16:09 UTC
![Screenshot_20221223_160519_K-9 Mail](https://user-images.githubusercontent.com/11923618/209365395-55be36d9-5f01-410f-acbf-3079e00bea85.jpg)

**Comment by dracos** [comment] 2023-01-05 12:34
Duplicate of https://github.com/mysociety/fixmystreet/issues/3768

**Closed by dracos** 2023-01-05 12:34 UTC
