### ISSUE TITLE
Option to mark reports as 'Closed'

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/fixmystreet#1339] opened 2016-02-25 16:33 UTC
User suggestion:

"At present there is only the option to mark a report "Fixed".  I have asked in the past if there was a way to "close" a report without labelling it as Fixed, if the problem has not actually been fixed. 

It seems wrong to mark a problem as fixed, when the problem still exists (usually this is where the council won't do it, won't admit responsibility, or are not actually responsible).

I think that I have in mind that at some point, councils are going to point to Fix My Street and say "there, we have fixed XX% of the reports, what a wonderful council we are" whereas this might not be the case.

When I look at "my reports" there is an option to filter them by Open, Fixed, or Closed: but there are no "closed" reports because the only option is to call them "fixed".

There are times when a report just needs to be closed, when it is clearly not going to be "fixed", but I completely agree that these reports should always remain visible, for all the reasons you mention on the site and in your reply.

So my question is, as the option to filter my reports by "closed" exists, can we please have the capacity to "close" a report without marking it as "fixed". Thus it remains as a failure, and there might come a time when it will be useful to be able to go through failed reports to see if there are any patterns.

**Comment by dracos** [comment] 2016-02-26 09:52
Dupe of #1340.

**Closed by dracos** 2016-02-26 09:52 UTC
