### ISSUE TITLE
`filter_category` parameter doesn't always carry through to report form [10hrs]

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#4118] opened 2022-09-23 10:49 UTC
The `filter_category` parameter can be used to prefilter the map & preselect a category when linking to FMS.

However the current behaviour doesn't seem to line up with the manual, which suggests the `filter_category` parameter [can be used on its own](https://www.fixmystreet.com/pro-manual/deep-linking/):

> [...]an extra parameter that will restrict the default map view and reporting to a particular category[...]

For example this link will prefilter the map to Graffiti reports but doesn't select that subcategory on the reporting form (even if the user knows what top-level category to select): https://fixmystreet.merton.gov.uk/?filter_category=Graffiti

Including the `filter_group` parameter _does_ preselect the top-level category and subcategory: https://fixmystreet.merton.gov.uk/?filter_category=Graffiti&filter_group=Street%20Cleaning%20Problems%20or%20Weeds

However this doesn't always work, e.g. https://fix.bathnes.gov.uk/?filter_group=Drains%20and%20flooding&filter_category=Blocked%20drain:%20Blockage%20on%20surface will prefilter the map to all subcategories in 'Drains and flooding' and doesn't preselect the 'Blocked drain: Blockage on surface' subcategory.

### Work required

- [ ] Make sure `filter_category` parameter works as expected for all categories

Related to FD-2412.

**Comment by dracos** [comment] 2023-02-06 15:44
Closing this as basically duplicate of older #3782 (manual part in new ticket).

**Closed by dracos** 2023-02-06 15:44 UTC
Labels: Bug
