### ISSUE TITLE
Logo still doesn't look good in dark mode emails

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/fixmystreet#3959] opened 2022-06-03 01:47 UTC
As per https://github.com/mysociety/fixmystreet/issues/3768

A system email in dark mode looks like this
![Screenshot_20220603-024254_K-9 Mail](https://user-images.githubusercontent.com/11923618/171771012-3b549e98-7b0b-4f10-adcb-27b441054e42.jpg)

**Comment by dracos** [comment] 2023-01-05 12:34
Duplicate of https://github.com/mysociety/fixmystreet/issues/3768

**Closed by dracos** 2023-01-05 12:34 UTC
