### ISSUE TITLE
Problem upvoting (+1's)

### ISSUE THREAD

**Issue by stevenday** [mysociety/fixmystreet#1569] opened 2016-10-28 11:49 UTC
I think it would be great if users could "upvote" problems on FMS, to show their support for getting things fixed without having to supply a "me too" type comment or similar.

To elaborate:
- Users should be able to click a button or link somewhere to upvote the problems
- I guess we should communicate the votes to the council in some way, but we don't want to overwhelm them with more email they can't act on
- It would be cool if we could see which problems have the most votes, maybe nationally and locally, or per-council/ward
- We'd need to make sure it's quite frictionless, but also stop people gaming the system in some way
- I'm not sure where would be best to integrate this, but somewhere on the report page would probably make most sense

**Comment by dracos** [comment] 2016-11-15 16:25
Dupe of #958.

**Closed by dracos** 2016-11-15 16:25 UTC
Labels: Feature, z - Icebox
