### ISSUE TITLE
Show state changes in problem alert emails

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet#4901] opened 2024-03-28 12:34 UTC
User suggestion:

> When an issue is marked as “Fixed” I get this message from Southwark council:
> 
> “Thank you for reporting this issue. We apologise for any inconvenience this has caused you. We can assure you that your complaint is being investigated.”
> 
> But I don’t see that the issue was marked as “fixed” in the email you sent.
> 
> This is confusing because it sounds like the issue is still in progress and there’s nothing in the email to say that the issue is fixed.
> 
> Could you make it clearer in the email when an issue has been fixed?

Example email:

<img width="662" alt="image" src="https://github.com/mysociety/fixmystreet/assets/4776/8f863d59-a779-4257-a4eb-42971b62e3d2">

**Comment by dracos** [comment] 2024-03-28 14:29
https://github.com/mysociety/fixmystreet/blob/master/perllib/FixMyStreet/Script/Alerts.pm#L128-L137 is the code that I thought would indeed be putting state changes in alert emails? Not sure what's happening if they're not appearing...

**Comment by lizettal** [comment] 2024-04-02 10:18
Three hours to investigate the cause of the bug

**Comment by neprune** [comment] 2024-05-20 08:36
@lizettal Probably half a day

**Comment by lizettal** [comment] 2024-06-20 16:48
I was looking at this today and realised that the state change text in alert emails - see screenshot below.

<img width="663" alt="Screenshot 2024-06-20 at 3 12 31 PM" src="https://github.com/mysociety/fixmystreet/assets/87080212/98cbb818-d430-4091-9eac-87188ec54daa">
<img width="663" alt="Screenshot 2024-06-20 at 3 12 31 PM" src="https://github.com/mysociety/fixmystreet/assets/87080212/98cbb818-d430-4091-9eac-87188ec54daa">

**Comment by neprune** [comment] 2024-06-24 12:04
Was able to repro with Surrey. Was not able to repro with Southwark though. Still investigating.

**Comment by neprune** [comment] 2024-06-24 13:41
The thing I was able to reproduce is not the same scenario as the screenshot. In my case the missing status line was due to the alert subscription time starting after the updates that changed the report it from confirmed status, so the 'reopen' moving it back to confirmed didn't trigger the status line block https://github.com/mysociety/fixmystreet/blob/master/perllib/FixMyStreet/Script/Alerts.pm#L128-L137. I think this is a super niche scenario and not worth trying to address.

As for the screenshot, I realised this is from the [developer email preview page](https://surrey.staging.fixmystreet.com/_dev/email/alert-update?problem=25192) (which I didn't know existed!) which doesn't have the status update line that gets added when the alerts script runs.

I think it's worth a separate ticket if we want the text in the developer preview to be at parity with the actual alert email and include the status change line.

**Closed** 2024-06-24 13:42 UTC
