### ISSUE TITLE
Open Graph image and description for a problem could be much better

### ISSUE THREAD

**Issue by zarino** [mysociety/fixmystreet#1154] opened 2015-07-23 15:54 UTC
When I share a report on Facebook, here's what it looks like (where "Test" is the comment I've added to the post).

![screen shot 2015-07-23 at 11 31 53](https://cloud.githubusercontent.com/assets/739624/8848339/70b9f850-312e-11e5-8493-a676b9d64152.png)

The image is a 500px square showing the FMS logo and some building work in a cartoon style. I'm not sure how Facebook decides between showing the image in landscape ratio above the link details, or square beside them, but it clearly making the wrong decision here, and the image is cropped to the point of being totally unintelligible. It is also a really unappealing taupe colour.

I, personally, would expect to see either the FMS user-supplied problem photo, or, if there isn't one, then a screengrab of a map with a pin showing where the problem is.

The text content of the link could also do a much better job of describing the thing I've shared. The problem title is included in the heading, although "Viewing a problem" means nothing. The "Easily report X, Y, and Z…" text is just boilerplate describing FMS, rather than what I expect as a person sharing this thing which is a summary of the problem itself.

**Comment by dracos** [comment] 2015-07-23 16:12
Links/overlaps #613

**Comment by dracos** [comment] 2015-08-17 11:18
Duplicate of #613

**Closed by dracos** 2015-08-17 11:18 UTC
