### ISSUE TITLE
Body page covering multiple areas should zoom to extent of all areas (Area just shows the ocean)

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet#1095] opened 2015-04-21 09:46 UTC
I clicked on https://www.fixmystreet.com/reports/TransportNI+%28Northern%29 from the list of all reports, and the map just shows ocean. Can't seem to zoom out either.

**Comment by dracos** [comment] 2015-04-21 10:58
I can zoom out okay? The issue is caused by a combination of two things; nothing has been reported to this body (so the map can't centre itself based on that), and the body covers multiple areas (and it only centres itself on an area if there is one area). I guess if there are multiple areas it should track all their bounds and zoom to the extent of all of them.

**Comment by MyfanwyNixon** [comment] 2015-04-21 11:02
Oh ok, the zoom is working for me now; not sure why it didn't before, or maybe I just didn't click enough times.

**Comment by dracos** [comment] 2016-11-15 16:33
This was fixed by the pretty-area-highlighting stuff (multiple areas are zoomed to extent).

**Closed by dracos** 2016-11-15 16:33 UTC
Labels: UK specific
