### ISSUE TITLE
In admin, we should be able to change the category of a report

### ISSUE THREAD

**Issue by loran750** [mysociety/fixmystreet#1365] opened 2016-03-28 22:28 UTC
Hello

in the admin backend, in the edit report page, how could we modify the category of a report ?
A select drop down would be okay.
Why is it non editable ?

regards
Loran

**Comment by dracos** [comment] 2016-03-29 08:04
This is a duplicate of #400 (so I'll close this one). I would certainly like it to be possible, but it's not trivial because changing the category could change the body if you have multiple bodies. But yes, you should be able to.

**Closed by dracos** 2016-03-29 08:04 UTC
