### ISSUE TITLE
User workflow to open a new problem from an existing problem report

### ISSUE THREAD

**Issue by abimysoc** [mysociety/fixmystreet#1408] opened 2016-05-24 11:07 UTC
Some users are unable to figure out, when they are looking at an existing problem report, how to report something new.

The "Report" link in the header takes them back to the homepage (from where they can again make the mistake of clicking an existing problem report pin rather than placing a new one). So they try the "Report abuse" button and it gives them a form to fill in, and #1072 ensues, which is a symptom, not the real problem.

The obvious solution would be a big button that says "Report a new problem at this location".

**Comment by abimysoc** [comment] 2016-05-24 11:15
See also #536.

**Comment by dracos** [comment] 2016-05-24 14:18
Dupe of https://github.com/mysociety/fixmystreet/issues/393

**Closed by dracos** 2016-05-24 14:19 UTC
Labels: Backlog, Design
