### ISSUE TITLE
allow send-reports to accept a single report id (use --debug option?)

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fixmystreet#1335] opened 2016-02-17 18:22 UTC
One reason to run `bin/send-reports --debug` is to see the error message coming back (if it's failing to send, of course), but currently when we do this we're actually looping through all unsent reports. This is often OK but it's annoying when there's a single report under investigation.

So it would be handy to be able to pass in a single report ID and have the script not bother looping in such a case. Normally this is emphatically not what you want `send-reports` to do (it _should_ send all the reports!) so I propose it's only relevant in debug mode. In which case, how about allowing the `--debug` option to pass in an optional report id? Maybe one or other of these (the first way is probably better because it prevents the risk of its dangerous effect being overlooked).

```
bin/send-reports --debug --send-single-report=1234

bin/send-reports --debug=1234
```

**Comment by dracos** [comment] 2016-02-19 10:32
Dupe of #732.

**Closed by dracos** 2016-02-19 10:32 UTC
Labels: Feature, Small But Uncontentious
